### ISSUE TITLE
Cannot undeploy ACM after deploy/undeploy HoH

### ISSUE THREAD

**Issue by clyang82** [stolostron/multicluster-global-hub#19]
There is an external finalizer added to some ACM resources. e.g.: `PlacementRule`.
When I follow the HoH document to deploy the HoH and undeploy HoH, then deploy ACM. 
Cannot undeploy ACM successfully due to some namespaces are in terminating status `Some content in the namespace has finalizers remaining: hub-of-hubs.open-cluster-management.io/policy-cleanup in 1 resource instances`

```
apiVersion: v1
items:
- apiVersion: apps.open-cluster-management.io/v1
  kind: PlacementRule
  metadata:
    annotations:
      open-cluster-management.io/user-group: c3lzdGVtOmNsdXN0ZXItYWRtaW5zLHN5c3RlbTphdXRoZW50aWNhdGVk
      open-cluster-management.io/user-identity: a3ViZTphZG1pbg==
    creationTimestamp: "2021-12-27T08:49:08Z"
    deletionGracePeriodSeconds: 0
    deletionTimestamp: "2021-12-27T12:29:32Z"
    finalizers:
    - hub-of-hubs.open-cluster-management.io/placementrule-cleanup
    generation: 2
    managedFields:
    - apiVersion: apps.open-cluster-management.io/v1
      fieldsType: FieldsV1
      fieldsV1:
        f:metadata:
          f:finalizers:
            .: {}
            v:"hub-of-hubs.open-cluster-management.io/placementrule-cleanup": {}
      manager: manager
      operation: Update
      time: "2021-12-27T08:49:08Z"
```

Expected behaviour is delete the finalizer along with undeploy HoH.

**Comment by vMaroon** [comment]
In what namespace are these resources? Also, to be super sure, this happened while undeploying the hub of hubs (undeploy_hub_of_hubs.sh) and not the leaf hub?

@clyang82

**Comment by nirrozenbaum** [comment]
to my understanding that happened in HoH, not in LH.
I think in LH it's handled properly in the undeploy script.

unless we will be told otherwise, this is an issue in hub-of-hubs-spec-sync.
assigning @vadimeisenbergibm

**Comment by vadimeisenbergibm** [comment]
Note that this is a general issue for all the Hub-of-Hubs components that add finalizers: hub-of-hubs-spec-sync, leaf-hub-status-sync. To solve this, the undeploy scripts should go over all the resources and delete all the hub-of-hubs finalizers. 
@nirnaaman please decide on the priority of this issue.

**Comment by nirrozenbaum** [comment]
when talking about global resources (resources that are created from HoH and are then sent down to LHs), this is handled by the current undeploy script.
the part that guarantees the removal of finalizers is the deletion order in the script, where we first remove hoh-system namespace which triggers a delete event for all resources in the namespace, then the events are caught by the controllers that remove the finalizers. after that the LH controllers are removed as well.
https://github.com/open-cluster-management/hub-of-hubs/blob/main/deploy/undeploy_leaf_hub.sh#L12

see in this image, in the upper window I run undeploy LH, and in the lower window this triggers removal of finalizer:
![image](https://user-images.githubusercontent.com/19717747/147537033-80ad7285-9fdd-493f-99a7-4d6a8fc82242.png)

that being said, the same issue may happen in LH as well if one creates a local policy (user creates resource directly on the LH and not through HoH).

we can add logic that every controller that adds finalizer will remove it when receiving SIGTERM signal. this can be achieved in HoH by reading the resources from DB and remove finalizers and in LH by going over the resources in the bundle that is held in memory.

having said all the above, I think this issue is with low priority. 
there is a simple workaround, to delete the ACM resources from HoH before undeploying anything, which will trigger the removal of finalizers.

**Comment by clyang82** [comment]
close it in favor of https://github.com/stolostron/backlog/issues/25021
